name: Periodic time

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Replace with the desired Python version

    - name: Install dependencies
      
      run:
        python -m pip install --upgrade pip
        # pip install -r requirements.txt  # Create a requirements.txt file if needed

    - name: List directory contents
      run: ls -al
    - name: Run Python script
      run: python periodic_time1.py  # Replace with the actual name of your Python script

    
