name: Unit Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Choose your desired Python version

    - name: Install dependencies
      run: pip install -r requirements.txt  # If you have any external dependencies

    - name: Run unit tests
      run: python -m unittest discover -s tests -p "*test_algorithm.py"

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-reports
